Transcoder.WebApp.Web/Controllers/ConversionController.cs
using Core.Transcoder.DataAccess.ViewModels;
using Core.Transcoder.FFmpegWrapper;
using Core.Transcoder.Service;
using Core.Transcoder.Service.Utils;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Core.Transcoder.Service.Services;
using Core.Transcoder.PayPalMvc;
using Core.Transcoder.PayPalMvc.Enums;
using Core.Transcoder.DataAccess;
using Core.Transcoder.Utils.Resources;
using Vereyon.Web;

namespace Transcoder.WebApp.Web.Controllers
{
    public class ConversionController : Controller
    {
        PaypalService paypalService = new PaypalService();
        TASK_Service taskService = new TASK_Service();

        // GET: Conversion
        public ActionResult Index()
        {
            return RedirectToAction("Panier");
        }


        public ActionResult Panier()
        {
            int UserId = CookieUtil.GetUserId(this);
            if (UserId == 0)
                return RedirectToAction("Index", "Home");

            var panier = new TASK_Service().GetPanierViewModel(UserId);

            return View("Panier", panier);
        }
        [OutputCache(NoStore = true, Duration = 0)]
        public ActionResult MesConversions()
        {
            int UserId = CookieUtil.GetUserId(this);
            if (UserId == 0)
                return RedirectToAction("Index", "Home");

            var commandes = new TASK_Service().GetListCommandesViewModel(UserId);

            return View("ListCommandes", commandes);
        }


        public ActionResult AddConversion()
        {
            int UserId = CookieUtil.GetUserId(this);
            if (UserId == 0)
            {
                CreateTaskViewModel model = new TASK_Service().InitCreateTaskViewModelFromAnonymous();
                return View(model);
            }
            {
                CreateTaskViewModel model = new TASK_Service().InitCreateTaskViewModel(UserId);
                return View(model);
            }
        }

        [HttpPost]
        public ActionResult AddConversion(CreateTaskViewModel model)
        {
            //if (!ModelState.IsValid)
            //    return View(model);


            bool isEdited =  new TASK_Service().AddTaskByViewModel(model);
            FlashMessage.Confirmation(@UiStrings.add_conversion_message_added_to_cart);
            if (model.ShortEditUserViewModel.PK_ID_USER == 0)
            {
                return LoginAuto(model.ShortEditUserViewModel);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
        public ActionResult LoginAuto(ShortEditUserViewModel model)
        {
            model.Password = string.IsNullOrWhiteSpace(model.Password) ? "" : EncryptionUtil.Encrypt(model.Password);
            var user = new USER_Service().LoginUser(model.Username, model.Password);
            if (user != null)
            {
                SetCurrentUser(user.USERNAME, user.PK_ID_USER);

                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View(model);
            }
        }
        public void SetCurrentUser(string Username, int Pk_id_user)
        {
            HttpCookie Cookie = Request.Cookies["User"] ?? new HttpCookie("User");
            Cookie.Value = Username;

            Response.SetCookie(Cookie);

            HttpCookie CookieID = Request.Cookies["UserID"] ?? new HttpCookie("UserID");
            CookieID.Value = Pk_id_user.ToString();

            Response.SetCookie(CookieID);
        }
        [HttpGet]
        public ActionResult DeleteConversion(int id)
        {
            if(id != 0)
            {
               bool isDeleted = new TASK_Service().DeleteTaskById(id);
                if (isDeleted)
                    return RedirectToAction("Panier");
            }
            return RedirectToAction("Panier");
        }


        [HttpPost]
        public ActionResult ValiderPanier(PanierViewModel model)
        {
            ServicePointManager.Expect100Continue = true;
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

            if (!ModelState.IsValid)
                return View("Panier", model);

            Session["Panier"] = model;

            string serverURL = HttpContext.Request.Url.GetLeftPart(UriPartial.Authority) + VirtualPathUtility.ToAbsolute("~/");
            SetExpressCheckoutResponse transactionResponse = paypalService.SendPayPalSetExpressCheckoutRequest(model, serverURL);
            
            if (transactionResponse == null || transactionResponse.ResponseStatus != Core.Transcoder.PayPalMvc.Enums.ResponseType.Success)
            {
                string errorMessage = (transactionResponse == null) ? "Null Paypal Transaction Response" : transactionResponse.ErrorToString;
                Debug.WriteLine("Error initiating PayPal SetExpressCheckout transaction. Error: " + errorMessage);
                return RedirectToAction("Panier", model);
            }
            FlashMessage.Confirmation(UiStrings.add_conversion_message_cart_validated);
            return Redirect(string.Format(Configuration.Current.PayPalRedirectUrl, transactionResponse.TOKEN));
        }

        [HttpPost]
        public ActionResult UploadFromUrl(string url)
        {
            var client = new System.Net.WebClient();
            try
            {
                var localPath = new CONFIG_Service().GetConfigValueByName("FilesFromClientPath");
                string path = localPath + url.Substring(url.LastIndexOf('/') + 1);
                client.DownloadFile(url, path);
                FileInfo fileInfo = new FileInfo(path);
                VideoFile videoFile = new VideoFile(path);

                double VideoDuration = videoFile.Duration.TotalMinutes;
                // On génére le prix en fonction de la durée
                double price = PriceGeneratorUtil.GetPriceByDuration(VideoDuration);
                // On recupere le format de base de la video
                string format = fileInfo.Extension.Substring(fileInfo.Extension.LastIndexOf('.') + 1);
                var formatBase = new FORMAT_Service().GetFormatByName(format);


                // Si le format a été trouvé dans nos bases on va proposer les conversions liées possibles.
                if (formatBase != null)
                {
                    var listFormatTypes = new FORMAT_TYPE_Service().GetSelectListFormatTypeByFormat((int)formatBase.FK_ID_FORMAT_TYPE);

                    return Json(new
                    {
                        success = "true",
                        fileUrl = path,
                        fileLength = fileInfo.Length,
                        fileName = fileInfo.Name,
                        fileFormatBase = formatBase.PK_ID_FORMAT,
                        listFormatType = new SelectList(listFormatTypes, "Value", "Text"),
                        fileDuration = VideoDuration.ToString(),
                        filePrice = price.ToString()
                    });
                }
                else
                {
                    return Json(new { success = "false" });
                }
            }
            catch(Exception e)
            {
                return Json(new { success = "false" });
            }
        }
        [HttpPost]
        public ActionResult Upload()
        {
            if (Request.Files.Count > 0)
            {
                var file = Request.Files[0];

                string path = SaveFileInFolder(file);
                // On recupere le format de base de la video
                int indexOf = file.ContentType.LastIndexOf('/') + 1;
                string format = file.ContentType.Substring(indexOf);
                var formatBase = new FORMAT_Service().GetFormatByName(format);
                // On recupere les infos de la video
                VideoFile videoFile = new VideoFile(path);
                
                double VideoDuration = videoFile.Duration.TotalMinutes;
                // On génére le prix en fonction de la durée
                double price = PriceGeneratorUtil.GetPriceByDuration(VideoDuration);

                // Si le format a été trouvé dans nos bases on va proposer les conversions liées possibles.
                if (formatBase != null)
                {
                    var listFormatTypes = new FORMAT_TYPE_Service().GetSelectListFormatTypeByFormat((int)formatBase.FK_ID_FORMAT_TYPE);

                    return Json(new { success = "true", fileUrl = path, fileLength = file.ContentLength, fileName = file.FileName, fileFormatBase = formatBase.PK_ID_FORMAT,
                        listFormatType = new SelectList(listFormatTypes, "Value", "Text"), fileDuration =  VideoDuration.ToString(), filePrice = price.ToString()
                    });
                }
                else
                {
                    return Json(new { success = "false" });
                }
            }
            return Json(new { success = "false" });
        }

        [HttpGet]
        public ActionResult Telecharger(int id)
        {
            TASK task = new TASK_Service().GetTaskById(id);
            int index = task.FILE_URL_DESTINATION.LastIndexOf('\\') + 1;
            string file = task.FILE_URL_DESTINATION.Substring(index);
            DownloadFile(file, task.FILE_URL_DESTINATION);

            return RedirectToAction("MesConversions");
    }
        [HttpPost]
        public JsonResult GetFormatByFormatTypeAndFormatBase(string formatTypeId, string fileFormatBase)
        {
            int FormatTypeId = 0;
            int FileFormat = 0;
            int.TryParse(formatTypeId, out FormatTypeId);
            int.TryParse(fileFormatBase, out FileFormat);
            List<SelectListItem> slFormat = new FORMAT_Service().GetSelectListFormatByFormatTypeIdAndFormatBase(FormatTypeId, FileFormat);

Transcoder.WebApp.Web/Views/Conversion/ListCommandes.cshtml
@using Core.Transcoder.Utils.Resources
@model Core.Transcoder.DataAccess.ViewModels.ListCommandesViewModel
<head>
    <title>@UiStrings.myconversions_title</title>
    <meta http-equiv="refresh" content="1800" />
    <meta http-equiv="Cache-Control" content="no-cache" />
    <meta http-equiv="Pragma" content="no-cache" />
    <meta http-equiv="expires" content="0" />
</head>
@{
    ViewBag.Title = @UiStrings.listconversion_page_title;
}

    <div class="container">
        <div id="conversions">
            @{ Html.RenderPartial("_ListConversions", Model.ListOfConversions); }
        </div>
    </div>

@section Scripts
{
    <script>


    </script>
}

Transcoder.WebApp.Web/Views/Conversion/Panier.cshtml
@using Core.Transcoder.Utils.Resources
@model Core.Transcoder.DataAccess.ViewModels.PanierViewModel

<head>
    <title>@UiStrings.panier_title</title>
</head>
@{
    ViewBag.Title = @UiStrings.cart_page_title;
}

@using (Html.BeginForm("ValiderPanier", "Conversion", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(false, "", new { @class = "text-danger" })
<div class="container">
    <div id="conversions">
        @{ Html.RenderPartial("_ListConversions", Model.ListOfConversions); }
    </div>
    <hr />
    <div id="price">     
        @Html.HiddenFor(m => m.GlobalPrice)
        @Html.HiddenFor(m => m.TransactionId)
        @Html.HiddenFor(m => m.UserId)
        @Html.HiddenFor(m => m.PaypalTransactionId)
        
        <h4>@UiStrings.cart_order_amount<span style="float:right; color:green">@Html.DisplayFor(m => m.GlobalPrice) €</span></h4>
    </div>
    @if (Model.ListOfConversions.Count > 0)
    {
    <div id="validerPanier"  style="text-align:right; margin-top:50px;" >
        <button type="submit" class="btn btn-success"id="btnValiderPanier"><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span> Valider mon panier</button>
    </div>
    }
</div>
}
@section Scripts
{
    <script>


    </script>
}

Transcoder.WebApp.Web/Views/Conversion/_ListConversions.cshtml
@using Core.Transcoder.Utils.Resources
@using Microsoft.SqlServer.Server
@model List<Core.Transcoder.DataAccess.ViewModels.ListTaskViewModel>
<head>
    <title>@UiStrings.myconversions_title</title>

</head>
<p>
    @Html.ActionLink(@UiStrings.listconversion_button_add_conversion, "AddConversion",null, new { @class = "btn btn-primary" })
</p>

<table class="table table-striped table-condensed table-no-bordered" data-toggle="table" data-pagination="true" data-filter-control="true">
    <thead>
        <tr>
            @*<th data-field="PK_ID_TASK" data-sortable="true" data-filter-control="input">
               Id
            </th>*@
            <th data-field="FILE_URL_ACCESS" data-sortable="true" data-filter-control="input" width="10%" data-width="20%">
                @UiStrings.addconversion_form_filename
            </th>
            @*<th data-field="FORMAT_TYPE" data-sortable="true" data-filter-control="input">
                    @Html.DisplayNameFor(model => model.FORMAT_TYPE)
                </th>*@
            <th data-field="FORMAT_BASE" data-sortable="true" data-filter-control="input">
               @UiStrings.addconversion_form_originformat
            </th>
            <th data-field="FORMAT_CONVERT" data-sortable="true" data-filter-control="input">
               @UiStrings.addconversion_form_convertedformat
            </th>
            <th data-field="DURATION" data-sortable="true" data-filter-control="input">
                @UiStrings.addconversion_form_length
            </th>
            <th data-field="STATUS" data-sortable="true" data-filter-control="input">
                @UiStrings.addconversion_form_status
            </th>

            <th data-field="PRICE" data-sortable="true" data-filter-control="input"> 
                @UiStrings.addconversion_form_price
            </th>
            <th data-width="1px"></th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.ToList().Count(); i++)
        
            {
            <tr>
               
                <td>
                    @Html.HiddenFor(modelItem => Model.ToList()[i].FK_ID_USER, new { Name = "ListOfConversions[" + i + "].FK_ID_USER" })
                    @Html.HiddenFor(modelItem => Model.ToList()[i].PK_ID_TASK, new { Name = "ListOfConversions[" + i + "].PK_ID_TASK" })
                    @Html.HiddenFor(modelItem => Model.ToList()[i].FILE_URL_ACCESS, new { Name = "ListOfConversions[" + i + "].FILE_URL_ACCESS" })
                    @Html.DisplayFor(modelItem => Model.ToList()[i].FILE_URL_ACCESS, new { Name = "ListOfConversions[" + i + "].FILE_URL_ACCESS" })
                </td>
                <td>
                    @Html.HiddenFor(modelItem => Model.ToList()[i].FORMAT_BASE, new { Name = "ListOfConversions[" + i + "].FORMAT_BASE" })
                    @Html.DisplayFor(modelItem => Model.ToList()[i].FORMAT_BASE, new { Name = "ListOfConversions[" + i + "].FORMAT_BASE" })
                </td>
                <td>
                    @Html.HiddenFor(modelItem => Model.ToList()[i].FORMAT_CONVERT, new { Name = "ListOfConversions[" + i + "].FORMAT_CONVERT" })
                    @Html.DisplayFor(modelItem => Model.ToList()[i].FORMAT_CONVERT, new { Name = "ListOfConversions[" + i + "].FORMAT_CONVERT" })
                </td>
                <td>
                    @Html.HiddenFor(modelItem => Model.ToList()[i].DURATION, new { Name = "ListOfConversions[" + i + "].DURATION" })
                    @Html.DisplayFor(modelItem => Model.ToList()[i].DURATION, new { Name = "ListOfConversions[" + i + "].DURATION" }) minutes
                </td>
                <td>
                    @if (Model.ToList()[i].STATUS == "Effectue")
                    {
                        @Html.HiddenFor(modelItem => Model.ToList()[i].STATUS, new { Name = "ListOfConversions[" + i + "].STATUS" })
                        @*@Html.DisplayFor(modelItem => Model.ToList()[i].STATUS, new { Name = "ListOfConversions[" + i + "].STATUS" })*@
                        <span style="color:green;" class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                    }
                    else
                    {
                        <span style="color:orange;" class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
                       @Html.HiddenFor(modelItem => Model.ToList()[i].STATUS, new { Name = "ListOfConversions[" + i + "].STATUS" })
                       @*@Html.Raw(@UiStrings.addconversion_cart_added)*@
                    }
                </td>
                <td style="color:greenyellow;">
                    @Html.HiddenFor(modelItem => Model.ToList()[i].PRICE, new { Name = "ListOfConversions[" + i + "].PRICE" })
                    @Html.DisplayFor(modelItem => Model.ToList()[i].PRICE, new { Name = "ListOfConversions[" + i + "].PRICE" }) €
                </td>
                <td>
                    @if (Model.ToList()[i].IS_PAID == false)
                    {
                        @Html.ActionLink(@UiStrings.conversion_button_delete, "DeleteConversion", new { id = Model.ToList()[i].PK_ID_TASK }, new { @class = "btn btn-danger" })
                    }
                    else if(Model.ToList()[i].STATUS == "Effectue")
                    {
                        @Html.ActionLink(@UiStrings.conversion_button_download, "Telecharger", new { id = Model.ToList()[i].PK_ID_TASK }, new { @class = "btn btn-warning" })
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

Transcoder.WebApp.Web/Views/Conversion/_ShortUserEdit.cshtml
@model Core.Transcoder.DataAccess.ViewModels.ShortEditUserViewModel

        <div class="contentWrap" style="margin-top:8%">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.PK_ID_USER, new { Name = "ShortEditUserViewModel.PK_ID_USER" })

            <div class="form-group">
                    @Html.LabelFor(model => model.Email, new { @class = "form-label" })
                    @Html.TextBoxFor(model => model.Email, new { @class = "form-control", Name = "ShortEditUserViewModel.Email", @style = "width: 80%; display: inline-block;" })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
            @if (Model.PK_ID_USER != 0)
            {
            <div class="form-group">
                    @Html.LabelFor(model => model.Firstname, new { @class = "form-label" })<br />
                    @Html.TextBoxFor(model => model.Firstname, new { @class = "form-control", Name = "ShortEditUserViewModel.Firstname", @style = "width: 80%; display: inline-block;" })
                    @Html.ValidationMessageFor(model => model.Firstname, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                    @Html.LabelFor(model => model.Lastname, new { @class = "form-label" })
                    @Html.TextBoxFor(model => model.Lastname, new { @class = "form-control", Name = "ShortEditUserViewModel.Lastname", @style = "width: 80%; display: inline-block;" })
                    @Html.ValidationMessageFor(model => model.Lastname, "", new { @class = "text-danger" })
            </div>
            }
            else
            {
                @Html.HiddenFor(model => model.Firstname, new { Name = "ShortEditUserViewModel.Firstname" })
                @Html.HiddenFor(model => model.Lastname , new { Name = "ShortEditUserViewModel.Lastname" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Username, new { @class = "form-label" })<br />
                    @Html.TextBoxFor(model => model.Username, new { @class = "form-control", Name = "ShortEditUserViewModel.Username", @style = "width: 80%; display: inline-block;" })
                    @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Password, new { @class = "form-label" })<br />
                    @Html.PasswordFor(model => model.Password, new { @class = "form-control", Name = "ShortEditUserViewModel.Password", @style = "width: 80%; display: inline-block;" })
                </div> 
            }
           </div>